GET http://localhost:8787/build

###
POST http://localhost:8787/build
Content-Type: application/javascript

< ./App1.js

###

GET http://localhost:8787/build/github

###
GET http://localhost:8787/build/github/RoyalIcing/Collected/app-react/src/components/Row.js?children=Children&summary
